# Generated by Django 3.2.7 on 2022-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0002_review_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category.jpg', upload_to='categories'),
        ),
    ]
