# Generated by Django 3.2 on 2024-11-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
