# Generated by Django 3.2.7 on 2022-04-20 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
