# Generated by Django 3.2.7 on 2022-04-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220423_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_confirmed',
            new_name='is_activated',
        ),
    ]
