# Generated by Django 3.2.7 on 2022-04-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_confirmed_customuser_is_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_activated',
            new_name='is_confirmed',
        ),
    ]
