# Generated by Django 3.2.7 on 2022-04-25 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscellenous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True)),
                ('image', models.ImageField(default='ingredients/default_ingredient.jpg', upload_to='ingredients')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('preparation_time', models.TimeField(default=datetime.time)),
                ('cooking_time', models.TimeField(default=datetime.time)),
                ('rest_time', models.TimeField(default=datetime.time)),
                ('difficulty', models.CharField(choices=[('v', 'Very Easy'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], max_length=1)),
                ('cost', models.CharField(choices=[('c', 'Cheap'), ('m', 'Medium'), ('e', 'Expensive')], max_length=1)),
                ('num_of_dishes', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='miscellenous.category')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True)),
                ('image', models.ImageField(default='utensils/default_utensil.jpg', upload_to='utensils')),
            ],
            options={
                'verbose_name': 'Utensil',
                'verbose_name_plural': 'Utensils',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UtensilItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utensils', to='recipes.recipe')),
                ('utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.utensil')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipe_images')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Image',
                'verbose_name_plural': 'Recipe Images',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('unit', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
