# Generated by Django 3.2.7 on 2022-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='default_ingredient.jpg', upload_to='ingredients'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='image',
            field=models.ImageField(default='default_utensil.jpg', upload_to='utensils'),
        ),
    ]
